version: '3.5'

services:
  db:
    image: postgres:14.3-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=realworld
    ports:
      - "5432:5432"